language: node_js

node_js:
  - 12

addons:
  apt:
    packages:
      # cypress dep
      - libgconf-2-4

cache:
  yarn: true

install:
  - yarn --frozen-lockfile

script:
  - yarn lint
  - rm -rf .cache
  - yarn build
  - yarn test:ci
