language: node_js

node_js:
  - '10'

addons:
  apt:
    packages:
      # cypress dep
      - libgconf-2-4

cache:
  yarn: true

install:
  - yarn install

script:
  - yarn lint
  - yarn build
  - yarn serve &
  - yarn cy:run
